import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/cupertino.dart';
import 'posts.dart';

class PostsService{
  FirebaseFirestore _fireStore = FirebaseFirestore.instance;
  String _currentID ="0";
  PostsService(){
    _currentID = _autoGeneratedID();
  }
  void putPost(Posts posts){
      _fireStore.collection("posts").doc(_autoGeneratedID()).set(posts.makeData());
  }
  void updatePost(UpdatePosts updatePosts, String doc){
      _fireStore.collection("posts").doc(doc).update(updatePosts.makeUpdateData());
  }
  void deletePost(String doc){
    _fireStore.collection("posts").doc(doc).delete();
  }

  String _autoGeneratedID(){
    int tmp = int.parse(_currentID);
    ++tmp;
    _currentID = tmp.toString();
    return _currentID;
  }

  String getCurrentID(){
    return _currentID;
  }

  void _getItemCount() async{
    StreamBuilder<QuerySnapshot>(
      stream: _fireStore.collection('posts').snapshots(),
      builder: (context,snapshot){
        final items = snapshot.data.docs;
        _currentID = items.length.toString();
        return Container();
      },
    );
  }

}

